extends:
  - stylelint-config-standard
  - stylelint-config-sass-guidelines
rules:
  max-nesting-depth: 10
  declaration-colon-newline-after: null
  at-rule-empty-line-before: null
  block-closing-brace-newline-after:
    - always
    - ignoreAtRules:
        - if
        - else
  selector-class-pattern: null
  selector-max-id: 1
  no-descending-specificity: null
  selector-type-no-unknown: null
