runtime: nodejs12

env_variables:
  PRISMIC_API_TOKEN: MC5YeWlyWlJFQUFDSUFpUF9D.77-977-977-977-977-9KO-_ve-_vTxv77-9aEjvv71E77-977-9Ue-_vWDvv71Nc2Hvv71E77-9QR3vv71K77-9
  PRISMIC_REPOSITORY_NAME: nextbase
  PRISMIC_REPOSITORY_LOCALE: en-us
  PRISMIC_HOME_ID: Xys95BIAACEAA3dm
